### PR TITLE
Feature/add support for swift package manager

### PR DESCRIPTION
**Pull request by darhaywa**

### CODE REVIEW

**Review by felginep — APPROVED** [review]

**Comment by felginep** [comment]
Thanks for the PR !

**Comment by darhaywa** [comment]
You’re welcome, I was hoping to get this tagged, but it seems to have failed due to SwiftLint, and I can’t see why.

From: Pierre Felgines ***@***.***>
Date: Friday, 18 June 2021 at 07:53
To: faberNovel/ADAssertLayout ***@***.***>
Cc: Daren Hayward ***@***.***>, Author ***@***.***>
Subject: Re: [faberNovel/ADAssertLayout] Feature/add support for swift package manager (#7)

Thanks for the PR !

**Comment by darhaywa** [comment]
Ah, found it!

[06:56:44]: ▸ /Users/runner/work/ADAssertLayout/ADAssertLayout/ADAssertLayout/Classes/UIView+LayoutTest.swift:18:12: warning: Cyclomatic Complexity Violation: Function should have complexity 10 or less: currently complexity equals 11 (cyclomatic_complexity)
231<https://github.com/faberNovel/ADAssertLayout/runs/2855980202#step:6:231>

This change didn’t modify that though….

Can it still be tagged or does this need fixing first?

From: Daren Hayward ***@***.***>
Date: Friday, 18 June 2021 at 08:39
To: faberNovel/ADAssertLayout ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [faberNovel/ADAssertLayout] Feature/add support for swift package manager (#7)
You’re welcome, I was hoping to get this tagged, but it seems to have failed due to SwiftLint, and I can’t see why.

From: Pierre Felgines ***@***.***>
Date: Friday, 18 June 2021 at 07:53
To: faberNovel/ADAssertLayout ***@***.***>
Cc: Daren Hayward ***@***.***>, Author ***@***.***>
Subject: Re: [faberNovel/ADAssertLayout] Feature/add support for swift package manager (#7)

Thanks for the PR !

**Comment by felginep** [comment]
I guess you can target the branch `develop` until I create a new release. Will try to do it today

**Comment by felginep** [comment]
Version [1.0.1](https://github.com/faberNovel/ADAssertLayout/releases/tag/v1.0.1) is released.

**Comment by darhaywa** [comment]
Thank you!

From: Pierre Felgines ***@***.***>
Date: Friday, 18 June 2021 at 09:59
To: faberNovel/ADAssertLayout ***@***.***>
Cc: Daren Hayward ***@***.***>, Author ***@***.***>
Subject: Re: [faberNovel/ADAssertLayout] Feature/add support for swift package manager (#7)

Version 1.0.1<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FfaberNovel%2FADAssertLayout%2Freleases%2Ftag%2Fv1.0.1&data=04%7C01%7Cdarhaywa%40synamedia.com%7C89d02edb94b84a8e46ca08d9323755be%7Cecdd899a33be4c3391e41f1144fc2f56%7C0%7C0%7C637596035501345991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0FT6biqMJfQndv2ViHalqrjrulE2%2ByZaKZACmTApGQw%3D&reserved=0> is released.

**Pull request merged**
